### ISSUE TITLE
Bug: Doesn’t work with @most/core

### ISSUE THREAD

**Issue by hoichi** [mostjs-community/last#1]
`last` doesn’t seem to work with @most/core. It’s defined as `stream => new stream.constructor(new Last(stream.source))`. But if `stream` is returned by, say, `take`, `stream.constructor` ends up pointing to `Slice` that takes `min` as the first value, so a `Last` instance ends up in the `min` position and the whole conundrum ends up in `Cannot read property 'run' of undefined`.

I can totally make a PR myself, but since I’m new to the most ecosystem, I'm worried my fix will break some backward compatibility.

**Comment by TylorS** [comment]
Hello @hoichi, thanks for reaching out. Support for `@most/core` is in fact a breaking change, but one definitely worth making. A PR would be very welcomed

**Comment by hoichi** [comment]
Will do. Give me a few days.

**Comment by hoichi** [comment]
@TylorS I’ve asked whether to use Northbrook or Lerna on Northbrook’ gitter, but—do you think it’s a good idea at all? Is, say, Lerna popular and useful enough that we expect anyone willing to contribute to a small OSS package to use it?

**Comment by TylorS** [comment]
Sorry, I don't frequent gitter nearly as much as I used to. I'd definitely recommend using Lerna as almost all of the the features I felt Lerna was lacking at the time of starting Northbrook have been addressed and merged into Lerna.

**Comment by hoichi** [comment]
Yeah, but isn’t it better to just drop Northbrook and use plain NPM? That’s what `@Frikki` suggested on Gitter, given that `last` is not a monorepo, and that’s what I feel as well: for me as a contributor who wants to simply fix one small package, things like Lerna or Northbrook are rather a hindrance than a help.

**Comment by TylorS** [comment]
Agreed 100%, getting started here is probably not as easy as it should be, and I haven't been active enough to keep on top of things. I agree it'd be a great step to simplify things to just NPM scripts.

I opened #2 to track that as well

**Comment by hoichi** [comment]
Gotcha, hope to get to both of them soon.

**Comment by TylorS** [comment]
@hoichi Thanks again for #3. I've gone ahead and sent you an invite as a collaborator here. You can use that as much or as little as you'd like 😀

**Comment by hoichi** [comment]
Hehe, I already _was_ a collaborator at `mostjs-community`. Meaning I probably didn’t have to fork `most-last`. Oh well ¯\_(ツ)_/¯
Thanks anyway! Hope to get around to fixing `@most/core` compatibility this week.

**Comment by hoichi** [comment]
Pushed tags for both 1.0.1 and 2.0 but I think I won’t publish 2.0 until `rollup-plugin-buba` is fixed.

**Comment by TylorS** [comment]
I spoke with David Chase, and he expressed the underlying project of buba, `buble`, is no longer maintained. It may be better to move to a purely Babel setup instead

**Comment by hoichi** [comment]
Or we could switch to TS and transpile without Babel. The upside would be auto-generated typings. The downside is that TypeScript cannot match the rich options of Babel env preset, like `targets: { "node": "current" }`.

But then if we transpile on `prepublish`, which is what npm docs recommend, it’s safer to transpile to ES5 anyway. Then again, `most` streams are supposed to be performant (and mostly run on client), and ES5 is slower, so...

I think I need to read more on modules and Rollup :confounded:

**Comment by TylorS** [comment]
I'm okay with switching to TypeScript. All of my new projects are. I had only used the https://github.com/mostjs/package-starter setup at one point in time here.

**Comment by hoichi** [comment]
Noob question: what is `dist/` used for? `"main"` in `package.json` points to `lib/`.

**Comment by TylorS** [comment]
It's a UMD build which can be used as a `<script>` tag

**Comment by hoichi** [comment]
Oh. Thanks. Not sure a lot of ppl will want to use single most packages off various CDNs, but building TS with Rollup totally works, so I guess I’m going to leave it )

Unless you think I should remove it, of course.

**Comment by TylorS** [comment]
I think it's okay to leave, you never know when someone is going to use something like jsbin and need a quick script. It widens the possible audience 😄

**Comment by hoichi** [comment]
Added a PR with one comment for ya. Haven’t bumped the version or anything yet. Not sure if it’s a minor or a fix or what ⊙﹏⊙

**Comment by hoichi** [comment]
Aaand... published. Closing it.

**Comment by TylorS** [comment]
Thank you for all your work @hoichi
