### ISSUE TITLE
Simplify getting started 

### ISSUE THREAD

**Issue by TylorS** [mostjs-community/last#2]
- [ ] Switch to NPM scripts from Northbrook

**Comment by hoichi** [comment]
A couple of questions.

1. What to do with Northbrook-related tasks in package.json? I guess we drop `commit`, but do we drop `release` as well, or can we do something useful via plain npm?
2. What about versions? I’m thinking to drop Northbrook in v1, and then fork v2 from that. But, if you agree with that, what version should v1 be? `1.0.1`? `1.1.0`?

I don’t suppose any dependent packages call `npm run commit` or `npm run release`, so it probably doesn’t matter much, but then I have zero xp with maintaining oss packages.

**Comment by hoichi** [comment]
@TylorS, should we close it? Or is there anything else I can do here?

And I don’t think I can publish the new version on NPM '^_^

**Comment by TylorS** [comment]
I think we can. If your NPM username is the same as your Github handle I gave you permissions on NPM as well!

**Comment by TylorS** [comment]
Thanks for all your help @hoichi!

**Comment by hoichi** [comment]
Yeah, I’m `hoichi` on NPM as well. Thanks!
